### PR TITLE
Add PTPPPSCR register to ETH_TypeDef

### PR DESCRIPTION
**Pull request by maribu**
### Contribution Description

Added the PTPPPSCR (PTP pulse-per-second control register) to the ETH_TypeDef.

### CODE REVIEW

**Comment by ALABSTM** [comment]
Hi @maribu,

Thank you for this contribution. Please let me introduce @CHAMSTM who will review your change.

With regards,

**Comment by ALABSTM** [comment]
Hi @maribu,

The point you raised through this p-r is relevant. Indeed, register **PTPPPSCR** is mentioned in our reference manuals and, hence, shall be added into our CMSIS Device header files.

Thank you again for your contribution. Your request will be logged into our internal database and an update will be made available soon hopefully.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 101024

**Review by ALABSTM — CHANGES_REQUESTED** [review]
Hi @maribu,

Thank you for this contribution. To complete the update would you mind adding the corresponding bits definition shown below?

Thanks,

```diff
#define ETH_PTPTSSR_TSSO                              ETH_PTPTSSR_TSSO_Msk     /* Time stamp seconds overflow */
+
+/* Bit definition for Ethernet PTP PPS Control Register */
+#define ETH_PTPPPSCR_PPSFREQ_Pos                      (0U)
+#define ETH_PTPPPSCR_PPSFREQ_Msk                      (0x0FUL << ETH_PTPPPSCR_PPSFREQ_Pos) /*!< 0x0000000F */
+#define ETH_PTPPPSCR_PPSFREQ                          ETH_PTPPPSCR_PPSFREQ_Msk    /*  PPS frequency selection */
```

**Comment by maribu** [comment]
Done. May I squash the two commits into one?

**Review by ALABSTM — APPROVED** [review]

**Comment by ALABSTM** [comment]
Hi @maribu,

Do not bother yourself. The "squash and merge" option will take care of this. Again, thank you for your contribution. Looking forward to receiving other contributions.

With regards,

**Comment by maribu** [comment]
Thanks for the review :-)

**Pull request merged**
